# Generated by Django 2.0.4 on 2018-04-11 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_choice', models.CharField(max_length=10, null=True)),
                ('seed_choice', models.CharField(max_length=100, null=True)),
                ('win_status', models.NullBooleanField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.Round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
