# Generated by Django 2.0.4 on 2018-04-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_scoreboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
