# Generated by Django 2.0.4 on 2018-04-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_round_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='winning_seed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='round',
            name='winning_slot',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
