# Generated by Django 2.0.4 on 2018-04-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20180411_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='winning_seed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='winning_slot',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
